package:
  name: control_cluster_bridge 
  version: 0.1.0  

source:
  path: .     # Path to the directory containing your built distribution artifacts

requirements:
  build:
    - python=3.7
    - flit
  run:
    - python=3.7

about:
  home: https://github.com/AndrePatri/CoClusterBridge
  license: MIT
  summary: Utilities to create a CPU-based control cluster to be interfaced with GPU-based simulators using shared memory for minimum latency.

extra:
  recipe-maintainers:  
    - AndrePatri
    
    
